// Code generated by mysql2proto. DO NOT EDIT.

syntax = "proto3";
package cbpb;

option go_package = "gitlab.dy/reborn/reborn-pb/cbpb";
option csharp_namespace = "Assets.Script.Reborn.Proto.Cbpb";

message {{ .TableName }}List {
    repeated {{ .TableName }} base_table = 1;
}

message {{ .TableName }} {
    {{- range .ProtoColumns}}
    {{ .ColumnType }} {{ .ColumnName }} = {{ .ColumnNum }};
    {{- end}}
}
